[window]
dimensions = { columns = 160, lines = 50 }

[font]
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }

[colors]
draw_bold_text_with_bright_colors = true

# colors from: https://github.com/alebelcor/alacritty-snazzy/tree/master
primary = { foreground = "#eff0eb", background = "#282a36" }
cursor = { cursor = "#97979b" }
selection = { text = "#282a36", background = "#feffff" }

[colors.normal]
black = "#282a36"
red = "#ff5c57"
green = "#5af78e"
yellow = "#f3f99d"
blue = "#57c7ff"
magenta = "#ff6ac1"
cyan = "#9aedfe"
white = "#f1f1f0"

[colors.bright]
black = '#686868'
red = '#ff5c57'
green = '#5af78e'
yellow = '#f3f99d'
blue = '#57c7ff'
magenta = '#ff6ac1'
cyan = '#9aedfe'
white = '#eff0eb'
